### ISSUE TITLE
Implement SearchByPlayerAttributes

### ISSUE THREAD

**Issue by 1izardo** [CSC207-UofT/course-project-team-scouts#34]
# To-do

- [x] prompting user to select which attributes they're interested in (defense, offense, etc.)
- [x] prompting user to specify value(s) for each individual attribute
- [x] dealing with unexpected input
